### ISSUE TITLE
please help me. when i sh run.sh

### ISSUE THREAD

**Issue by QiShanZhang** [RjDuan/AdvCam-Hide-Adv-with-Natural-Styles#22]
sh run.sh 
2022-11-25 19:58:32.674867: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2022-11-25 19:58:32.676762: I tensorflow/core/common_runtime/process_util.cc:63] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
('Top1: ', 'n06794110 street sign', 0.38263422)
('Top5: ', [('n06794110 street sign', 0.38263422), ('n02840245 binder, ring-binder', 0.1255164), ('n04141975 scale, weighing machine', 0.06438678), ('n07248320 book jacket, dust cover, dust jacket, dust wrapper', 0.053751726), ('n03666591 lighter, light, igniter, ignitor', 0.039573323)])
Setting up style layer: <conv1_1/Relu:0>
Setting up style layer: <conv2_1/Relu:0>
Setting up style layer: <conv3_1/Relu:0>
Setting up style layer: <conv4_1/Relu:0>
Setting up style layer: <conv5_1/Relu:0>
Traceback (most recent call last):
  File "advcam_main.py", line 84, in <module>
    attack(args)
  File "/home/hutao/AdvCam-Hide-Adv-with-Natural-Styles/advcam_physical_attack.py", line 205, in attack
    ],feed_dict={physical_adaptor.background: physical_adaptor.select_random_background(content_width,content_height)})
  File "/home/hutao/AdvCam-Hide-Adv-with-Natural-Styles/physical_adaption_utils.py", line 91, in select_random_background
    files = os.listdir(self.bg_path)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by QiShanZhang** [comment]
thank you very much , i have already solve it by change advcam_main.py line 21 --background_path
